[build]
publish = "_site"
command = """
    curl -fsSL https://deno.land/x/install/install.sh | sh && \
    /opt/buildhome/.deno/bin/deno task build \
  """

[[redirects]]
from = "/*.css"
to = "/:splat"
status = 200
force = true



[[redirects]]
from = "/*"
to = "/:splat"
status = 200
conditions = { Cookie = "is-disclamer-accepted" }

[[redirects]]
from = "/*"
to = "/instruction"
force = true
status = 200
